apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: policy-hub-eks
  region: us-east-1
  version: "1.31"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 30
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        ebs: true

# We'll install Cilium after cluster creation
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
