apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-deathstar-access-from-empire-pods
spec:
  # This policy allows only pods with the label "org=empire" to access the deathstar service
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toPorts:
    - ports:
      - port: "80"
