#!/bin/bash
# =============================================================================
# KPH LLM Security Demo - Apply Security Policies
# =============================================================================
# This script applies the Cilium, Tetragon, and NGINX Gateway Fabric security
# policies generated by Kubernetes Policy Hub.
#
# Usage: ./apply-policies.sh [cilium|tetragon|ngf|all]
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_policy() { echo -e "${CYAN}[KPH]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# =============================================================================
# Apply Cilium Network Policies
# =============================================================================
apply_cilium_policies() {
    echo ""
    echo "============================================================="
    log_policy "Applying Cilium Network Policies"
    echo "============================================================="
    echo ""
    
    log_info "These policies were generated by KPH from natural language intent:"
    echo ""
    echo "  Intent: 'Ollama should only communicate with OpenWebUI."
    echo "           Block ALL internet egress to prevent data exfiltration.'"
    echo ""
    echo "  Intent: 'OpenWebUI should only connect to internal Ollama."
    echo "           Block external connections to prevent SSE injection.'"
    echo ""
    echo "  Intent: 'Prevent DNS tunneling by restricting to cluster DNS.'"
    echo ""

    log_info "Applying Cilium policies..."
    kubectl apply -f "${PROJECT_DIR}/manifests/cilium-policies/"

    echo ""
    log_success "Cilium network policies applied"
    echo ""
    
    # Show applied policies
    log_info "Policies now active:"
    kubectl get ciliumnetworkpolicies -A
}

# =============================================================================
# Apply Tetragon Tracing Policies
# =============================================================================
apply_tetragon_policies() {
    echo ""
    echo "============================================================="
    log_policy "Applying Tetragon Runtime Security Policies"
    echo "============================================================="
    echo ""
    
    log_info "These policies were generated by KPH from natural language intent:"
    echo ""
    echo "  Intent: 'If any shell process spawns inside the Ollama pod,"
    echo "           kill it immediately and alert.'"
    echo ""
    echo "  Intent: 'Block curl, wget, nc, and Python execution in"
    echo "           LLM pods to prevent exploitation.'"
    echo ""
    echo "  Intent: 'Alert when model files are accessed. Detect"
    echo "           potential model theft attempts.'"
    echo ""

    log_info "Applying Tetragon policies..."
    kubectl apply -f "${PROJECT_DIR}/manifests/tetragon-policies/"

    echo ""
    log_success "Tetragon tracing policies applied"
    echo ""
    
    # Show applied policies
    log_info "Policies now active:"
    kubectl get tracingpolicies -A
}

# =============================================================================
# Apply NGINX Gateway Fabric Policies
# =============================================================================
apply_ngf_policies() {
    echo ""
    echo "============================================================="
    log_policy "Applying NGINX Gateway Fabric Security Policies"
    echo "============================================================="
    echo ""
    
    log_info "These policies were generated by KPH from natural language intent:"
    echo ""
    echo "  Intent: 'Add security headers to all responses to protect"
    echo "           against XSS, clickjacking, and MIME sniffing.'"
    echo ""
    echo "  Intent: 'Block direct access to internal API endpoints"
    echo "           like /ollama/ and /admin/ from external clients.'"
    echo ""

    log_info "Applying NGF policies..."
    kubectl apply -f "${PROJECT_DIR}/manifests/ngf-policies/"

    echo ""
    log_success "NGINX Gateway Fabric policies applied"
    echo ""
    
    # Show applied policies
    log_info "HTTPRoutes configured:"
    kubectl get httproutes -A
}

# =============================================================================
# Show Policy Summary
# =============================================================================
show_summary() {
    echo ""
    echo "============================================================="
    log_success "KPH Security Policies Applied Successfully"
    echo "============================================================="
    echo ""
    echo "L7 Ingress Security (NGINX Gateway Fabric):"
    echo "  ✅ Security headers (XSS, clickjacking protection)"
    echo "  ✅ Internal API endpoints blocked (/ollama/, /admin/)"
    echo ""
    echo "L3/L4 Network Security (Cilium):"
    echo "  ✅ Ollama egress restricted to OpenWebUI only"
    echo "  ✅ OpenWebUI egress restricted to Ollama only"
    echo "  ✅ DNS exfiltration prevention enabled"
    echo "  ✅ Default deny policies active"
    echo ""
    echo "Runtime Security (Tetragon):"
    echo "  ✅ Shell execution blocked in LLM pods"
    echo "  ✅ Network tools (curl/wget/nc) blocked"
    echo "  ✅ Model file access auditing enabled"
    echo "  ✅ Privilege escalation detection active"
    echo "  ✅ Cryptominer detection active"
    echo ""
    echo "Next steps:"
    echo "  1. Run './demo-attacks.sh' again to verify attacks are blocked"
    echo "  2. Open Hubble UI (http://localhost:8081) to see flow visibility"
    echo "  3. Check Tetragon events:"
    echo "     kubectl logs -n kube-system -l app.kubernetes.io/name=tetragon -f"
    echo ""
}

# =============================================================================
# Main
# =============================================================================
main() {
    echo ""
    echo "============================================================="
    echo "  Kubernetes Policy Hub - Applying Security Policies"
    echo "============================================================="
    
    case "${1:-all}" in
        cilium)
            apply_cilium_policies
            ;;
        tetragon)
            apply_tetragon_policies
            ;;
        ngf)
            apply_ngf_policies
            ;;
        all)
            apply_ngf_policies
            apply_cilium_policies
            apply_tetragon_policies
            show_summary
            ;;
        *)
            echo "Usage: $0 [cilium|tetragon|ngf|all]"
            exit 1
            ;;
    esac
}

main "$@"
