name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      options:
        - Docker Compose
        - Helm Chart
        - Manual Kubernetes
        - Local Development
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: KPH Version
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any relevant environment details
      placeholder: |
        - Kubernetes version:
        - Cloud provider:
        - Browser (if UI issue):

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant logs (will be automatically formatted)
      render: shell
